### ISSUE TITLE
Repeated messages

### ISSUE THREAD

**Issue by ADevaux42** [juliendelplanque/lcddaemon#10]
When a message is poped from the queue, but this message must be repeated at least one time, the message is pushed again in the queue.

The problem is, by calling push on the message, you reset the "added_date" attribute by calling "set_added_date_now()". The fact is, the meaning of "added_date" is correct, but its use isn't. We use the "added_date" attribute to check if the message is outdated. So, if the added_date is already set (pre-existing), it shouldn't be reset. Because, only the first push date of the message is important, it's from this date/time that the outdated property is checked.

**Comment by juliendelplanque** [comment]
In fact there is a second issue hidding in this:

```
    def pop(self):
        """ Pop the first message from the queue.
            This operation is thread-safe.
        """
        m = self.queue.get()
        while m.is_outdated():
            m = self.queue.get()
        users[m.sender] -= 1
        if m.repeat > 1:
            m.repeat = m.repeat - 1
            self.put(m)
        return m

    def put(self, message):
        """ Put a message at the end of the queue.
            This operation is thread-safe.
        """
        if self.user_reached_limit(message.sender):
            raise UserException("You have too much messages waiting in the queue.",
                                exceptions.TOO_MUCH_MESSAGES)
        self.queue.put(message)
        message.set_added_date_now()
        if message.sender in self.users:
            self.users[message.sender] += 1
        else:
            self.users[message.sender] = 0
        print("Message added in the queue - "+str(message.added_date))
```

Let's say a user has as much messages in the queue as the limit authorize him and we are not lucky,  we pop one of its message with a repeat > 1, he put a message in the queue. Then, when pop() function will try to re-put the message that has to be repeated, an exception will occur and this exception is not managed in pop() method. So the server will crash.

We need to find a way to deal with this.

**Comment by ADevaux42** [comment]
We should use a semaphore by user, in that way, each users can continue to process their own messages, while a message that must be repeated can cause this problem.

**Comment by juliendelplanque** [comment]
Fixed!
